//! Real ROS 2 backend built on [`rclrs`] (DDS).
//!
//! # This module does not compile without ROS 2
//!
//! It is gated behind `--features ros2` and can only be built inside a **colcon
//! workspace** that provides the generated message crates (`std_msgs`), because:
//!
//! * `rclrs` links the ROS 2 C libraries (`rcl`, `rmw`) — it needs a sourced ROS
//!   install to compile at all.
//! * `std_msgs` is generated by `rosidl_rust` via colcon; it is not on crates.io.
//!
//! Plain `cargo build` (the default `sim` feature) never compiles this file, so
//! CI stays ROS-free. The rclrs calls below were checked against the **rclrs
//! 0.7.0** source (types, QoS builder, callback bounds) but have not yet been
//! compiled on a ROS box — see `docs/ros2_integration.md`.
//!
//! # Design
//!
//! A dedicated OS thread owns the rclrs `Context`/executor and spins it. clankeRS's
//! tokio examples talk to it through channels, so example code keeps its async
//! `publish` / `subscribe().next().await` shape — no rclrs callback rewrite. The
//! public API (`RobotNode`, `Publisher`, `Subscriber`) is identical to the sim
//! backend.
//!
//! # Transport
//!
//! For the MVP, every clankeRS message is carried as `std_msgs/String` holding
//! the message's JSON (via [`RosMessage::serialize`]/[`RosMessage::deserialize`]).
//! This makes the backend generic over any `M: RosMessage` without per-type
//! wiring. Typed `sensor_msgs/Image` bridging (see [`crate::bridge::image`]) is
//! the next step for wire-compatibility with stock ROS nodes.

use std::marker::PhantomData;
use std::thread::JoinHandle;

use tokio::sync::mpsc;

use clankers_core::{RobotError, RobotResult};
// `IntoPrimitiveOptions` brings the `.qos(..)` combinator on topic names into scope.
use rclrs::IntoPrimitiveOptions;

use crate::message::RosMessage;
use crate::qos::{Durability, QosProfile, Reliability};

// Provided by the colcon overlay (declared in package.xml).
use std_msgs::msg::String as RosString;

/// ROS 2 node handle backed by an rclrs executor thread.
pub struct RobotNode {
    // `rclrs::Node` is already `Arc<NodeState>`, so it is cheap to clone and
    // safe to use from the async side while the executor thread spins.
    node: rclrs::Node,
    _executor: JoinHandle<()>,
    name: String,
}

impl RobotNode {
    pub async fn new(name: impl Into<String>) -> RobotResult<Self> {
        let name = name.into();
        // rclrs reads ROS_DOMAIN_ID (and other args) from the environment.
        let context = rclrs::Context::default_from_env()
            .map_err(|e| RobotError::Other(format!("rclrs context: {e}")))?;
        let mut executor = context.create_basic_executor();
        let node = executor
            .create_node(name.as_str())
            .map_err(|e| RobotError::Other(format!("rclrs node '{name}': {e}")))?;

        // The executor blocks, so it gets its own thread. The Node handle stays
        // on the async side to create publishers/subscriptions.
        let handle = std::thread::Builder::new()
            .name(format!("rclrs-exec-{name}"))
            .spawn(move || {
                let _ = executor.spin(rclrs::SpinOptions::default());
            })
            .map_err(|e| RobotError::Other(format!("spawn rclrs executor: {e}")))?;

        tracing::info!(node = %name, "starting clankeRS node (rclrs/DDS backend)");
        Ok(Self {
            node,
            _executor: handle,
            name,
        })
    }

    pub async fn publish<M: RosMessage>(
        &self,
        topic: &str,
        qos: QosProfile,
    ) -> RobotResult<Publisher<M>> {
        let publisher = self
            .node
            .create_publisher::<RosString>(topic.qos(to_rclrs_qos(qos)))
            .map_err(|e| RobotError::Other(format!("create_publisher {topic}: {e}")))?;
        Ok(Publisher {
            publisher,
            topic: topic.to_string(),
            _marker: PhantomData,
        })
    }

    pub async fn subscribe<M: RosMessage>(
        &self,
        topic: &str,
        qos: QosProfile,
    ) -> RobotResult<Subscriber<M>> {
        let (tx, rx) = mpsc::unbounded_channel::<Vec<u8>>();
        // Node subscription callbacks are `Fn(T) + Send + Sync`; an mpsc sender
        // satisfies that and hands the bytes to the async `next()` side.
        let subscription = self
            .node
            .create_subscription::<RosString, _>(
                topic.qos(to_rclrs_qos(qos)),
                move |msg: RosString| {
                    let _ = tx.send(msg.data.into_bytes());
                },
            )
            .map_err(|e| RobotError::Other(format!("create_subscription {topic}: {e}")))?;
        Ok(Subscriber {
            rx,
            _subscription: subscription,
            topic: topic.to_string(),
            _marker: PhantomData,
        })
    }

    pub fn name(&self) -> &str {
        &self.name
    }
}

pub struct Publisher<M> {
    // `rclrs::Publisher<T>` is `Arc<PublisherState<T>>`.
    publisher: rclrs::Publisher<RosString>,
    topic: String,
    _marker: PhantomData<M>,
}

impl<M: RosMessage> Publisher<M> {
    pub fn topic(&self) -> &str {
        &self.topic
    }

    pub async fn publish(&self, msg: M) -> RobotResult<()> {
        let json = String::from_utf8(msg.serialize())
            .map_err(|e| RobotError::Other(format!("message not utf-8: {e}")))?;
        self.publisher
            .publish(&RosString { data: json })
            .map_err(|e| RobotError::Other(format!("publish {}: {e}", self.topic)))?;
        Ok(())
    }
}

pub struct Subscriber<M> {
    rx: mpsc::UnboundedReceiver<Vec<u8>>,
    // Held so the rclrs subscription (`Arc<SubscriptionState>`) is not dropped
    // while we poll.
    _subscription: rclrs::Subscription<RosString>,
    topic: String,
    _marker: PhantomData<M>,
}

impl<M: RosMessage> Subscriber<M> {
    pub fn topic(&self) -> &str {
        &self.topic
    }

    pub async fn next(&mut self) -> Option<M> {
        loop {
            let bytes = self.rx.recv().await?;
            match M::deserialize(&bytes) {
                Ok(msg) => return Some(msg),
                Err(e) => tracing::warn!(error = %e, topic = %self.topic, "deserialize failed"),
            }
        }
    }
}

/// Map a clankeRS [`QosProfile`] to an rclrs [`rclrs::QoSProfile`] via the
/// builder methods on `QOS_PROFILE_DEFAULT`.
fn to_rclrs_qos(qos: QosProfile) -> rclrs::QoSProfile {
    let profile = rclrs::QOS_PROFILE_DEFAULT.keep_last(qos.history_depth as u32);
    let profile = match qos.reliability {
        Reliability::Reliable => profile.reliable(),
        Reliability::BestEffort => profile.best_effort(),
    };
    match qos.durability {
        Durability::Volatile => profile.volatile(),
        Durability::TransientLocal => profile.transient_local(),
    }
}
