//! Real ROS 2 backend built on [`rclrs`] (DDS).
//!
//! # This crate only compiles inside a colcon workspace
//!
//! `rclrs` links the ROS 2 C libraries (`rcl`, `rmw`) — it needs a sourced ROS
//! install to compile at all — and the message crates (`sensor_msgs`,
//! `std_msgs`, `builtin_interfaces`) are generated by `rosidl_generator_rs` via
//! colcon, not published on crates.io. So this package is built by colcon inside
//! `ros2_ws/` (see `ros2/README.md`), never by the main `cargo build`.
//!
//! # Design
//!
//! A dedicated OS thread owns the rclrs `Executor` and spins it. clankeRS's tokio
//! examples talk to it through channels, so example code keeps its async
//! `publish` / `subscribe().next().await` shape — no rclrs callback rewrite. The
//! public API (`RobotNode`, `Publisher`, `Subscriber`) is identical to the sim
//! backend, and the shared message/QoS types come from the [`clankers_ros2`]
//! core crate.
//!
//! On drop, [`RobotNode`] halts the executor and joins its thread before the
//! rclrs `Context` is torn down, so the spinning thread never races context
//! shutdown (which otherwise prints a benign `rmw_publish.cpp` line at exit).
//!
//! # Transport
//!
//! The wire type is chosen per message via [`RosMessage::wire_type`]:
//!
//! * [`WireType::Image`] (e.g. [`ImageMsg`]) is published/subscribed as a real
//!   `sensor_msgs/Image` through the typed bridge in [`crate::bridge::image`],
//!   so stock ROS nodes (`ros2 topic echo`, Foxglove, `v4l2_camera`, bag play)
//!   interoperate directly.
//! * [`WireType::StringJson`] (the default, used by `DetectionArray` until it
//!   gets a custom `.msg`) is carried as `std_msgs/String` holding the message
//!   JSON. This keeps the backend generic over any `M: RosMessage` with no
//!   per-type wiring.
//!
//! Dispatch is a runtime `match` on `M::wire_type()`; the typed arm recovers the
//! concrete `ImageMsg` by downcasting (`wire_type() == Image` is only ever
//! implemented by `ImageMsg`). Internally the subscriber channel always carries
//! clankeRS JSON bytes, so `Subscriber::next` stays uniform — a typed image is
//! converted to [`ImageMsg`] in the DDS callback before being queued.

use std::any::Any;
use std::marker::PhantomData;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::thread::JoinHandle;
use std::time::Duration;

use tokio::sync::mpsc;

use clankers_core::{RobotError, RobotResult};
// Trait imports for methods rclrs attaches via extension traits:
// * `CreateBasicExecutor` -> `Context::create_basic_executor`
// * `IntoPrimitiveOptions` -> the `.qos(..)` combinator on topic names
use rclrs::{CreateBasicExecutor, IntoPrimitiveOptions};

use crate::bridge;
use clankers_ros2::message::{ImageMsg, RosMessage, WireType};
use clankers_ros2::qos::{Durability, QosProfile, Reliability};

// Provided by the colcon overlay (declared in package.xml).
use sensor_msgs::msg::Image as RosImage;
use std_msgs::msg::String as RosString;

/// ROS 2 node handle backed by an rclrs executor thread.
pub struct RobotNode {
    // `rclrs::Node` is already `Arc<NodeState>`, so it is cheap to clone and
    // safe to use from the async side while the executor thread spins.
    node: rclrs::Node,
    // Wakes an in-progress spin slice so `Drop` doesn't wait out the full spin
    // timeout. Wraps a clone of the executor's `ExecutorCommands`, taken before
    // the executor moves onto its thread. Boxed as a closure so this field's type
    // doesn't hard-code rclrs's export path for `ExecutorCommands`.
    halt: Box<dyn Fn() + Send + Sync>,
    // Set true in `Drop` to break the spin loop (checked between spin slices).
    stop: Arc<AtomicBool>,
    // `Option` so `Drop` can `take()` and join the thread exactly once.
    executor: Option<JoinHandle<()>>,
    name: String,
}

impl RobotNode {
    pub async fn new(name: impl Into<String>) -> RobotResult<Self> {
        let name = name.into();
        // rclrs reads ROS_DOMAIN_ID (and other args) from the environment.
        let context = rclrs::Context::default_from_env()
            .map_err(|e| RobotError::Other(format!("rclrs context: {e}")))?;
        let mut executor = context.create_basic_executor();
        let node = executor
            .create_node(name.as_str())
            .map_err(|e| RobotError::Other(format!("rclrs node '{name}': {e}")))?;

        // Grab a wakeup handle before the executor is moved onto its thread, so
        // `Drop` can wake an in-progress spin slice. `commands()` returns
        // `&Arc<ExecutorCommands>`; the clone is `Send + Sync`.
        let commands = Arc::clone(executor.commands());
        let halt: Box<dyn Fn() + Send + Sync> = Box::new(move || commands.halt_spinning());

        let stop = Arc::new(AtomicBool::new(false));
        let stop_thread = Arc::clone(&stop);

        // The executor blocks, so it gets its own thread. The Node handle stays on
        // the async side to create publishers/subscriptions. We spin in bounded
        // 100 ms slices and poll `stop` between them: a plain `spin()` with no
        // timeout never returns (verified against real Humble DDS — even
        // `halt_spinning()` does not release it), so the timeout is what lets
        // `Drop` stop the loop and join the thread instead of hanging on exit.
        let handle = std::thread::Builder::new()
            .name(format!("rclrs-exec-{name}"))
            .spawn(move || {
                while !stop_thread.load(Ordering::Relaxed) {
                    let _ = executor
                        .spin(rclrs::SpinOptions::default().timeout(Duration::from_millis(100)));
                }
            })
            .map_err(|e| RobotError::Other(format!("spawn rclrs executor: {e}")))?;

        tracing::info!(node = %name, "starting clankeRS node (rclrs/DDS backend)");
        Ok(Self {
            node,
            halt,
            stop,
            executor: Some(handle),
            name,
        })
    }

    pub async fn publish<M: RosMessage>(
        &self,
        topic: &str,
        qos: QosProfile,
    ) -> RobotResult<Publisher<M>> {
        let qos = to_rclrs_qos(qos);
        let wire = match M::wire_type() {
            WireType::Image => WirePublisher::Image(
                self.node
                    .create_publisher::<RosImage>(topic.qos(qos))
                    .map_err(|e| RobotError::Other(format!("create_publisher {topic}: {e}")))?,
            ),
            WireType::StringJson => WirePublisher::Str(
                self.node
                    .create_publisher::<RosString>(topic.qos(qos))
                    .map_err(|e| RobotError::Other(format!("create_publisher {topic}: {e}")))?,
            ),
        };
        Ok(Publisher {
            wire,
            topic: topic.to_string(),
            _marker: PhantomData,
        })
    }

    pub async fn subscribe<M: RosMessage>(
        &self,
        topic: &str,
        qos: QosProfile,
    ) -> RobotResult<Subscriber<M>> {
        // The channel always carries clankeRS JSON bytes so `next()` can decode
        // uniformly via `M::deserialize`, regardless of the DDS wire type.
        let (tx, rx) = mpsc::unbounded_channel::<Vec<u8>>();
        let qos = to_rclrs_qos(qos);
        // Node subscription callbacks are `Fn(T) + Send + Sync`; an mpsc sender
        // satisfies that and hands the bytes to the async `next()` side.
        let subscription = match M::wire_type() {
            WireType::Image => WireSubscription::Image(
                self.node
                    .create_subscription::<RosImage, _>(topic.qos(qos), move |msg: RosImage| {
                        // Real sensor_msgs/Image -> ImageMsg -> JSON bytes.
                        let _ = tx.send(bridge::image::from_ros(&msg).serialize());
                    })
                    .map_err(|e| RobotError::Other(format!("create_subscription {topic}: {e}")))?,
            ),
            WireType::StringJson => WireSubscription::Str(
                self.node
                    .create_subscription::<RosString, _>(topic.qos(qos), move |msg: RosString| {
                        let _ = tx.send(msg.data.into_bytes());
                    })
                    .map_err(|e| RobotError::Other(format!("create_subscription {topic}: {e}")))?,
            ),
        };
        Ok(Subscriber {
            rx,
            _subscription: subscription,
            topic: topic.to_string(),
            _marker: PhantomData,
        })
    }

    pub fn name(&self) -> &str {
        &self.name
    }
}

impl Drop for RobotNode {
    fn drop(&mut self) {
        // Break the spin loop, wake any in-progress spin slice, then join, so the
        // executor thread is no longer touching DDS when the rclrs `Context` is
        // torn down. Without this the process would hang on exit (the spin thread
        // never returns) — and it also avoids the benign `cannot publish data ...
        // rmw_publish.cpp` line at teardown.
        self.stop.store(true, Ordering::Relaxed);
        (self.halt)();
        if let Some(handle) = self.executor.take() {
            let _ = handle.join();
        }
    }
}

/// Concrete rclrs publisher chosen by [`RosMessage::wire_type`].
/// `rclrs::Publisher<T>` is `Arc<PublisherState<T>>`.
enum WirePublisher {
    Str(rclrs::Publisher<RosString>),
    Image(rclrs::Publisher<RosImage>),
}

pub struct Publisher<M> {
    wire: WirePublisher,
    topic: String,
    _marker: PhantomData<M>,
}

impl<M: RosMessage> Publisher<M> {
    pub fn topic(&self) -> &str {
        &self.topic
    }

    pub async fn publish(&self, msg: M) -> RobotResult<()> {
        match &self.wire {
            WirePublisher::Str(publisher) => {
                let json = String::from_utf8(msg.serialize())
                    .map_err(|e| RobotError::Other(format!("message not utf-8: {e}")))?;
                publisher
                    .publish(&RosString { data: json })
                    .map_err(|e| RobotError::Other(format!("publish {}: {e}", self.topic)))?;
            }
            WirePublisher::Image(publisher) => {
                // Invariant: `wire_type() == Image` is implemented only by
                // `ImageMsg`, so this downcast always succeeds.
                let img = (&msg as &dyn Any)
                    .downcast_ref::<ImageMsg>()
                    .ok_or_else(|| {
                        RobotError::Other(format!(
                            "topic {} uses WireType::Image but message is not ImageMsg",
                            self.topic
                        ))
                    })?;
                publisher
                    .publish(&bridge::image::to_ros(img))
                    .map_err(|e| RobotError::Other(format!("publish {}: {e}", self.topic)))?;
            }
        }
        Ok(())
    }
}

/// Concrete rclrs subscription chosen by [`RosMessage::wire_type`].
/// `rclrs::Subscription<T>` is `Arc<SubscriptionState<T>>`.
enum WireSubscription {
    Str(rclrs::Subscription<RosString>),
    Image(rclrs::Subscription<RosImage>),
}

pub struct Subscriber<M> {
    rx: mpsc::UnboundedReceiver<Vec<u8>>,
    // Held so the rclrs subscription is not dropped while we poll.
    _subscription: WireSubscription,
    topic: String,
    _marker: PhantomData<M>,
}

impl<M: RosMessage> Subscriber<M> {
    pub fn topic(&self) -> &str {
        &self.topic
    }

    pub async fn next(&mut self) -> Option<M> {
        loop {
            let bytes = self.rx.recv().await?;
            match M::deserialize(&bytes) {
                Ok(msg) => return Some(msg),
                Err(e) => tracing::warn!(error = %e, topic = %self.topic, "deserialize failed"),
            }
        }
    }
}

/// Map a clankeRS [`QosProfile`] to an rclrs [`rclrs::QoSProfile`] via the
/// builder methods on `QOS_PROFILE_DEFAULT`.
fn to_rclrs_qos(qos: QosProfile) -> rclrs::QoSProfile {
    let profile = rclrs::QOS_PROFILE_DEFAULT.keep_last(qos.history_depth as u32);
    let profile = match qos.reliability {
        Reliability::Reliable => profile.reliable(),
        Reliability::BestEffort => profile.best_effort(),
    };
    match qos.durability {
        Durability::Volatile => profile.volatile(),
        Durability::TransientLocal => profile.transient_local(),
    }
}
