/* clankeRS C ABI — see cpp/README.md for C++ wrappers. */
#ifndef CLANKERS_H
#define CLANKERS_H

/* Warning, this file is autogenerated by cbindgen. Don't modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * ABI version — bump when breaking the C API layout or semantics.
 */
#define CLANKERS_ABI_VERSION 1

/**
 * Maximum tensor rank exposed through the C API.
 */
#define CLANKERS_MAX_RANK 6



/**
 * Element dtype.
 */
typedef enum ClankersDType {
  CLANKERS_D_TYPE_BOOL = 0,
  CLANKERS_D_TYPE_U8 = 1,
  CLANKERS_D_TYPE_F16 = 2,
  CLANKERS_D_TYPE_F32 = 3,
  CLANKERS_D_TYPE_F64 = 4,
  CLANKERS_D_TYPE_I32 = 5,
  CLANKERS_D_TYPE_I64 = 6,
} ClankersDType;

/**
 * Device placement.
 */
typedef enum ClankersDevice {
  CLANKERS_DEVICE_CPU = 0,
  CLANKERS_DEVICE_CUDA = 1,
  CLANKERS_DEVICE_METAL = 2,
} ClankersDevice;

/**
 * Memory layout of a tensor buffer.
 */
typedef enum ClankersLayout {
  CLANKERS_LAYOUT_CONTIGUOUS = 0,
  CLANKERS_LAYOUT_STRIDED = 1,
} ClankersLayout;

/**
 * Function status / error code.
 */
typedef enum ClankersStatus {
  CLANKERS_STATUS_OK = 0,
  CLANKERS_STATUS_INVALID_ARG = 1,
  CLANKERS_STATUS_MODEL_LOAD = 2,
  CLANKERS_STATUS_INVALID_INPUT = 3,
  CLANKERS_STATUS_BACKEND = 4,
  CLANKERS_STATUS_ALLOCATION = 5,
  CLANKERS_STATUS_NULL_POINTER = 6,
  CLANKERS_STATUS_INTERNAL = 7,
  CLANKERS_STATUS_UNSUPPORTED = 8,
  CLANKERS_STATUS_CONFIG = 9,
} ClankersStatus;

/**
 * Opaque engine builder handle.
 */
typedef struct ClankersEngineBuilder {
  uint8_t _private[0];
} ClankersEngineBuilder;

/**
 * Opaque inference engine handle.
 */
typedef struct ClankersEngine {
  uint8_t _private[0];
} ClankersEngine;

/**
 * Concrete tensor shape.
 */
typedef struct ClankersShape {
  size_t dims[CLANKERS_MAX_RANK];
  size_t rank;
} ClankersShape;

/**
 * Description of one model input or output tensor.
 */
typedef struct ClankersTensorSpec {
  const char *name;
  enum ClankersDType dtype;
  struct ClankersShape shape;
  enum ClankersLayout layout;
} ClankersTensorSpec;

/**
 * Borrowed read-only tensor view (caller owns `data`).
 */
typedef struct ClankersTensorView {
  const uint8_t *data;
  size_t byte_len;
  enum ClankersDType dtype;
  struct ClankersShape shape;
  enum ClankersLayout layout;
  enum ClankersDevice device;
} ClankersTensorView;

/**
 * Opaque owned tensor handle returned from `clankers_engine_run`.
 */
typedef struct ClankersTensor {
  uint8_t _private[0];
} ClankersTensor;

/**
 * Borrowed writable tensor view (caller owns `data`).
 */
typedef struct ClankersTensorViewMut {
  uint8_t *data;
  size_t byte_len;
  enum ClankersDType dtype;
  struct ClankersShape shape;
  enum ClankersLayout layout;
  enum ClankersDevice device;
} ClankersTensorViewMut;

/**
 * Per-run inference accounting.
 */
typedef struct ClankersInferenceStats {
  uint64_t latency_us;
  size_t copies;
  size_t bytes_copied;
  size_t allocations;
  size_t bytes_allocated;
  uint64_t backend_latency_us;
  size_t backend_copies;
  size_t backend_bytes_copied;
} ClankersInferenceStats;

/**
 * A named input for `clankers_engine_run_named`.
 */
typedef struct ClankersNamedInput {
  const char *name;
  struct ClankersTensorView view;
} ClankersNamedInput;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the stable C ABI version number.
 */
uint32_t clankers_abi_version(void);

/**
 * Build an engine from a configured builder. On success, `*out_engine` is set
 * and the builder is consumed (do not destroy it).
 */
enum ClankersStatus clankers_engine_builder_build(struct ClankersEngineBuilder *builder,
                                                  struct ClankersEngine **out_engine);

/**
 * Destroy an engine builder (safe on null).
 */
void clankers_engine_builder_destroy(struct ClankersEngineBuilder *builder);

/**
 * Create a new engine builder.
 */
struct ClankersEngineBuilder *clankers_engine_builder_new(void);

/**
 * Select backend: `"noop"` or `"onnxruntime"`.
 */
enum ClankersStatus clankers_engine_builder_set_backend(struct ClankersEngineBuilder *builder,
                                                        const char *backend);

/**
 * Set the model file path (required for `onnxruntime` backend).
 */
enum ClankersStatus clankers_engine_builder_set_model_path(struct ClankersEngineBuilder *builder,
                                                           const char *path);

/**
 * Configure the identity shape used by the `noop` backend (default `[1, 4]`).
 */
enum ClankersStatus clankers_engine_builder_set_noop_shape(struct ClankersEngineBuilder *builder,
                                                           const size_t *dims,
                                                           size_t rank);

/**
 * Reserved profiling toggle (stats are always available via run_with_stats).
 */
enum ClankersStatus clankers_engine_builder_set_profiling(struct ClankersEngineBuilder *builder,
                                                          bool enabled);

/**
 * Enable strict real-time checks at build time.
 */
enum ClankersStatus clankers_engine_builder_set_strict_realtime(struct ClankersEngineBuilder *builder,
                                                                bool enabled);

/**
 * Set warm-up run count at build time.
 */
enum ClankersStatus clankers_engine_builder_set_warmup(struct ClankersEngineBuilder *builder,
                                                       uint32_t runs);

/**
 * Convenience: create an ONNX engine from a model path.
 */
enum ClankersStatus clankers_engine_create(const char *model_path,
                                           struct ClankersEngine **out_engine);

/**
 * Destroy an engine.
 */
enum ClankersStatus clankers_engine_destroy(struct ClankersEngine *engine);

/**
 * Number of model inputs.
 */
size_t clankers_engine_input_count(const struct ClankersEngine *engine);

/**
 * Fill `out_spec` with the input tensor spec at `index`.
 *
 * Free `out_spec.name` with [`clankers_tensor_spec_destroy`] when done.
 */
enum ClankersStatus clankers_engine_input_spec(const struct ClankersEngine *engine,
                                               size_t index,
                                               struct ClankersTensorSpec *out_spec);

/**
 * Number of model outputs.
 */
size_t clankers_engine_output_count(const struct ClankersEngine *engine);

/**
 * Fill `out_spec` with the output tensor spec at `index`.
 */
enum ClankersStatus clankers_engine_output_spec(const struct ClankersEngine *engine,
                                                size_t index,
                                                struct ClankersTensorSpec *out_spec);

/**
 * Run inference. Caller must destroy each output tensor and the output array.
 */
enum ClankersStatus clankers_engine_run(struct ClankersEngine *engine,
                                        const struct ClankersTensorView *inputs,
                                        size_t input_count,
                                        struct ClankersTensor ***out_outputs,
                                        size_t *out_output_count);

/**
 * Run inference into caller-preallocated output buffers (zero-alloc hot loop).
 */
enum ClankersStatus clankers_engine_run_into(struct ClankersEngine *engine,
                                             const struct ClankersTensorView *inputs,
                                             size_t input_count,
                                             struct ClankersTensorViewMut *outputs,
                                             size_t output_count,
                                             struct ClankersInferenceStats *out_stats);

/**
 * Run inference with named inputs (any order).
 */
enum ClankersStatus clankers_engine_run_named(struct ClankersEngine *engine,
                                              const struct ClankersNamedInput *named,
                                              size_t named_count,
                                              struct ClankersTensor ***out_outputs,
                                              size_t *out_output_count);

/**
 * Run inference and return per-run stats.
 */
enum ClankersStatus clankers_engine_run_with_stats(struct ClankersEngine *engine,
                                                   const struct ClankersTensorView *inputs,
                                                   size_t input_count,
                                                   struct ClankersTensor ***out_outputs,
                                                   size_t *out_output_count,
                                                   struct ClankersInferenceStats *out_stats);

/**
 * Returns the last error code set on this thread.
 */
enum ClankersStatus clankers_last_error_code(void);

/**
 * Returns a human-readable message for the last error on this thread.
 *
 * The pointer is valid until the next FFI call on the same thread.
 */
const char *clankers_last_error_message(void);

/**
 * Free the output pointer array returned by run functions (not the tensors).
 */
void clankers_output_array_destroy(struct ClankersTensor **outputs, size_t count);

/**
 * Frees a string allocated by clankeRS (reserved for future use).
 */
void clankers_string_destroy(char *ptr);

/**
 * Byte length of the tensor buffer.
 */
size_t clankers_tensor_byte_len(const struct ClankersTensor *tensor);

/**
 * Returns a pointer to the tensor's byte buffer (valid until destroy).
 */
const uint8_t *clankers_tensor_data(const struct ClankersTensor *tensor);

/**
 * Destroy an owned tensor allocated by clankeRS.
 */
enum ClankersStatus clankers_tensor_destroy(struct ClankersTensor *tensor);

/**
 * Element dtype of an owned tensor.
 */
enum ClankersDType clankers_tensor_dtype(const struct ClankersTensor *tensor);

/**
 * Shape of an owned tensor.
 */
struct ClankersShape clankers_tensor_shape(const struct ClankersTensor *tensor);

/**
 * Free the `name` field allocated by spec query functions.
 */
void clankers_tensor_spec_destroy(struct ClankersTensorSpec *spec);

/**
 * Build a borrowed view descriptor over caller-owned memory (zero-copy).
 *
 * `data` must remain valid for the lifetime of the inference call.
 */
enum ClankersStatus clankers_tensor_view_from_external(const uint8_t *data,
                                                       size_t byte_len,
                                                       enum ClankersDType dtype,
                                                       struct ClankersShape shape,
                                                       enum ClankersLayout layout,
                                                       struct ClankersTensorView *out_view);

/**
 * Build a borrowed mutable view descriptor over caller-owned memory.
 */
enum ClankersStatus clankers_tensor_view_mut_from_external(uint8_t *data,
                                                           size_t byte_len,
                                                           enum ClankersDType dtype,
                                                           struct ClankersShape shape,
                                                           enum ClankersLayout layout,
                                                           struct ClankersTensorViewMut *out_view);

/**
 * Returns the clankeRS release version string.
 */
const char *clankers_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CLANKERS_H */
