#!/usr/bin/env bash
#
# One-command bootstrap for the real rclrs/DDS backend.
#
# Builds a ROS 2 (Humble) + ros2-rust workspace, wires the checked-in clankeRS
# DDS packages (ros2/clankers-ros2-dds, ros2/pubsub_minimal_dds) into it, and
# colcon-builds the minimal publisher. This is ONLY needed for real DDS — the
# default `sim` backend and all of CI build with plain `cargo` and no ROS install.
#
# Prereqs: Ubuntu 22.04 with ROS 2 Humble installed (`ros-humble-ros-base`),
# `python3-vcstool`, `libclang-dev`, and a Rust toolchain >= 1.85. The provided
# .devcontainer/ has all of this.
#
# Usage:
#   source /opt/ros/humble/setup.bash
#   bash scripts/setup_ros2_ws.sh          # bootstrap + build pubsub_minimal_dds
#   source ros2_ws/install/setup.bash
#   ros2 run pubsub_minimal_dds pubsub_minimal_dds   # or: ros2/pubsub_minimal_dds/../..
#
# Then, from a second sourced shell:
#   ros2 topic type /camera/image_raw      # -> sensor_msgs/msg/Image
#   ros2 topic echo /camera/image_raw      # -> typed header/height/width/encoding/...
#
# See docs/ros2_integration.md for the full, verified-on-a-ROS-box flow.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WS="$REPO/ros2_ws"

if [ -z "${ROS_DISTRO:-}" ]; then
  echo "error: source your ROS 2 install first (e.g. 'source /opt/ros/humble/setup.bash')" >&2
  exit 1
fi

echo "==> Installing colcon + cargo-ament-build tooling"
python3 -m pip install --user \
  git+https://github.com/colcon/colcon-cargo.git \
  git+https://github.com/colcon/colcon-ros-cargo.git
cargo install --locked cargo-ament-build

echo "==> Creating ros2-rust workspace at $WS"
mkdir -p "$WS/src"
if [ ! -d "$WS/src/ros2_rust" ]; then
  git clone https://github.com/ros2-rust/ros2_rust.git "$WS/src/ros2_rust"
fi

echo "==> Importing message-generation dependencies"
vcs import "$WS/src" < "$WS/src/ros2_rust/ros2_rust_humble.repos"

echo "==> Building the ROS message crates (rclrs, std_msgs, sensor_msgs, ...)"
cd "$WS"
colcon build --packages-up-to sensor_msgs std_msgs rclrs

# colcon's generated .cargo/config.toml patches the message crates but NOT rclrs.
# The crates.io rclrs 0.7.0 is an older, API-incompatible release than the
# ros2-rust `main` rclrs colcon just built, so downstream cargo packages must
# patch rclrs to the local git source. Add it if missing.
CARGO_CFG="$WS/.cargo/config.toml"
if [ -f "$CARGO_CFG" ] && ! grep -q "patch.crates-io.rclrs" "$CARGO_CFG"; then
  echo "==> Adding [patch.crates-io.rclrs] -> src/ros2_rust/rclrs to $CARGO_CFG"
  cat >> "$CARGO_CFG" <<'EOF'

[patch.crates-io.rclrs]
path = "src/ros2_rust/rclrs"
EOF
fi

# ---------------------------------------------------------------------------
# Wire the checked-in clankeRS DDS packages into ros2_ws and build them.
# ---------------------------------------------------------------------------
echo "==> Symlinking ros2/ packages into $WS/src"
# -n so a re-run replaces the link instead of nesting inside the target dir.
ln -sfn "$REPO/ros2/clankers-ros2-dds" "$WS/src/clankers-ros2-dds"
ln -sfn "$REPO/ros2/pubsub_minimal_dds" "$WS/src/pubsub_minimal_dds"

# The symlinked packages canonicalize to $REPO/ros2/<pkg> at build time (getcwd
# resolves the symlink), so cargo would walk up from there and MISS
# $WS/.cargo/config.toml. Mirror the patch config to $REPO/ros2/.cargo/config.toml
# (discovered from the canonical package path) with every relative `path = "..."`
# rewritten to an absolute path into ros2_ws, so it resolves from either location.
if [ -f "$CARGO_CFG" ]; then
  echo "==> Generating $REPO/ros2/.cargo/config.toml (absolute patch paths)"
  mkdir -p "$REPO/ros2/.cargo"
  {
    echo "# AUTO-GENERATED by scripts/setup_ros2_ws.sh — do not edit or commit."
    echo "# Mirrors $CARGO_CFG with relative patch paths made absolute so the"
    echo "# colcon build of the symlinked ros2/ packages finds the message crates."
    echo
    # Prefix every relative patch `path = "X"` (X not starting with /) with "$WS/".
    # Four expressions cover {line-start, after-boundary} x {double, single quote},
    # so inline tables (foo = { path = "..." }) and dotted keys (foo.path = "...")
    # are all rewritten. Absolute paths (leading /) are left untouched. Portable
    # across GNU and BSD sed (no anchor-inside-group).
    sed -E \
      -e 's|^([[:space:]]*)path([[:space:]]*=[[:space:]]*")([^/"][^"]*)"|\1path\2'"$WS"'/\3"|' \
      -e 's|([[:space:]{,.])path([[:space:]]*=[[:space:]]*")([^/"][^"]*)"|\1path\2'"$WS"'/\3"|g' \
      -e "s|^([[:space:]]*)path([[:space:]]*=[[:space:]]*')([^/'][^']*)'|\\1path\\2${WS}/\\3'|" \
      -e "s|([[:space:]{,.])path([[:space:]]*=[[:space:]]*')([^/'][^']*)'|\\1path\\2${WS}/\\3'|g" \
      "$CARGO_CFG"
  } > "$REPO/ros2/.cargo/config.toml"
fi

echo "==> Building pubsub_minimal_dds (pulls in clankers-ros2-dds via cargo)"
colcon build --packages-up-to pubsub_minimal_dds

cat <<EOF

Done — the real rclrs/DDS backend is built.

Run the minimal publisher and verify the typed image on the ROS graph:

  source $WS/install/setup.bash
  ros2 run pubsub_minimal_dds pubsub_minimal_dds &

  # From a second sourced shell:
  ros2 topic type /camera/image_raw     # -> sensor_msgs/msg/Image
  ros2 topic echo /camera/image_raw     # -> typed header/height/width/encoding/step/data

The default clankeRS build (sim backend) and CI need NONE of this — plain
\`cargo build --workspace\` from the repo root stays ROS-free.

See docs/ros2_integration.md for details.
EOF
